id: 10b142568f4c45eaaface19f63f7ed05
initial_creation_type: ocr
source_metadata:
  volumes:
    d3ce87f31bbb4fcca2e578ed71cea7c1:
      base_file: v066.txt
      image_group_id: I1PD95912
      title: ''
      total_pages: 1529
      volume_number: 67
