id: D2B4040F4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-13T03:40:47+00:00'
last_modified: '2022-05-29T07:53:24.027844+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    d629:
      image_group_id: I1PD95912
      title: ''
      total_pages: 1529
      order: 67
      base_file: d629.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
